"""Real authenticated UI: adaptive intake and mobile task visibility, no network substitution."""
import json, os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
private=json.loads(Path(os.environ['CAD_NATIVE_E2E_PRIVATE']).read_text())
out=Path(os.environ['CAD_ACCEPTANCE_REPORT_DIR']);out.mkdir(parents=True,exist_ok=False);out.chmod(0o700)
with sync_playwright() as pw:
 b=pw.chromium.launch(headless=True);p=b.new_page(viewport={'width':390,'height':844});errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
 try:
  p.goto(os.getenv('CAD_NATIVE_E2E_WEB','http://127.0.0.1:8100'))
  p.locator('input[type=text]').fill(private['owner']['phone']);p.locator('input[type=password]').fill(private['owner']['password']);p.locator('button[type=submit]').click()
  expect(p.get_by_role('button',name='打开项目导航',exact=True)).to_be_visible()
  p.get_by_role('button',name='打开项目导航',exact=True).click()
  p.get_by_role('button',name=os.environ['CAD_LAYOUT_FAILED_TITLE'],exact=False).first.click()
  expect(p.get_by_test_id('authoritative-task')).to_be_visible()
  expect(p.get_by_test_id('authoritative-task')).to_have_attribute('data-task-phase','failed')
  p.get_by_role('button',name='预览',exact=True).click()
  alert=p.get_by_role('button',name='本次任务失败 · 点击处理',exact=True)
  expect(alert).to_be_visible();alert.click()
  expect(p.get_by_test_id('authoritative-task')).to_be_visible()
  p.screenshot(path=str(out/'mobile-failure.png'))
  p.get_by_role('button',name='折叠 Agent',exact=True).click()
  expect(alert).to_be_visible();alert.click()
  expect(p.get_by_test_id('authoritative-task')).to_be_visible()
  p.set_viewport_size({'width':1440,'height':1000})
  p.get_by_role('button',name='新建设计',exact=True).click()
  prompt=p.get_by_role('textbox',name='工程需求',exact=True)
  prompt.fill('创建一个 100×60×3 mm 的板');p.get_by_role('button',name='开始创建',exact=True).click()
  intake=p.get_by_role('region',name='执行前需求确认',exact=True)
  expect(intake.get_by_role('textbox',name='关键尺寸依据',exact=True)).to_have_value('100×60×3 mm')
  expect(intake.get_by_role('button',name='确认并执行',exact=True)).to_be_enabled()
  expect(intake.get_by_role('checkbox')).to_have_count(0)
  assert '适配未验证' not in intake.inner_text()
  expect(intake.get_by_role('textbox',name='尺寸来源说明',exact=True)).to_have_count(0)
  intake.get_by_role('textbox',name='关键尺寸依据',exact=True).fill('100×60×4 mm')
  expect(intake).to_contain_text('100×60×4 mm')
  p.screenshot(path=str(out/'explicit-geometry.png'))
  intake.get_by_role('button',name='返回修改',exact=True).click()
  prompt.fill('创建一个板');p.get_by_role('button',name='开始创建',exact=True).click()
  expect(intake.get_by_role('button',name='按概念外形继续',exact=True)).to_be_disabled()
  assert '适配未验证' not in intake.inner_text()
  intake.get_by_role('button',name='返回修改',exact=True).click()
  prompt.fill('制作适配 iPhone 的手机壳');p.get_by_role('button',name='开始创建',exact=True).click()
  expect(intake).to_contain_text('适配未验证')
  expect(intake.get_by_role('button',name='按概念外形继续',exact=True)).to_be_disabled()
  intake.get_by_role('checkbox',name='确认仅生成概念外形',exact=True).check()
  expect(intake.get_by_role('button',name='按概念外形继续',exact=True)).to_be_enabled()
  p.screenshot(path=str(out/'physical-fit.png'))
  assert not errors,errors
  (out/'report.json').write_text(json.dumps({'passed':True,'mobile_failure_action':True,'explicit_geometry_editable':True,'missing_dimensions_blocked':True,'physical_fit_unverified':True,'page_errors':errors},ensure_ascii=False,indent=2))
  print('INTAKE MOBILE PASSED')
 except BaseException:
  p.screenshot(path=str(out/'failure.png'));(out/'failure.txt').write_text(p.locator('body').inner_text());raise
 finally:b.close()
